fix ios accuracy
NativeScript/nativescript-geolocation pull request #200
Opened 2019-02-19 09:39 UTC by akera-io

When requesting a high accuracy for ios we often receive a not so accurate location due to the fact that when starting update location ios will send a first location as quick as possible although not with the desired accuracy so desiredAccuracy was basically ignored on ios. Since from version 9+ the requestLocation API was introduced thought to use that as well, still if timeout option is specified the good old timer must be used.

2019-02-27 07:24 UTC, VladimirAmiorkov approved these changes

2019-02-27 07:52 UTC, VladimirAmiorkov commented
Hi @akera-io ,

I see that there is an CI test that is failing in this PR, can you review it and review your PRs code. The first failure is here: https://travis-ci.org/NativeScript/nativescript-geolocation/jobs/495360697#L347 I see that the error is the same for all failed tests ("Failed: Error: iosLocManager.requestLocation is not a function. (In 'iosLocManager.requestLocation()', 'iosLocManager.requestLocation' is undefined)")

2019-02-27 07:52 UTC, VladimirAmiorkov requested changes
Unit test are failing with "Failed: Error: iosLocManager.requestLocation is not a function. (In 'iosLocManager.requestLocation()', 'iosLocManager.requestLocation' is undefined)"

2019-02-27 09:52 UTC, akera-io commented
Missed the 'mock' location manager used for tests, did added the new method there and tests seems to pass now.

2019-02-28 07:54 UTC, VladimirAmiorkov approved these changes

2019-02-28 07:54 UTC, merged

2019-02-28 07:54 UTC, VladimirAmiorkov commented
@akera-io Thank you. We will proceed with testing and will publish a new version as soon as possible.

2019-02-28 08:02 UTC, elena-p commented
implementation of feature https://github.com/NativeScript/nativescript-geolocation/issues/202